spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: ResumeFlow
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours
  affinda:
    api-key: ${AFFINDA_API_KEY}
    workspace-id: ${AFFINDA_WORKSPACE_ID}
    collection-id: ${AFFINDA_COLLECTION_ID}
  openrouter:
    api-key: ${OPENROUTER_API_KEY}
