spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: ResumeFlow
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:dummy_secret}
    expiration: 86400000 # 24 hours
  affinda:
    api-key: ${AFFINDA_API_KEY:dummy_key}
    workspace-id: ${AFFINDA_WORKSPACE_ID:dummy_workspace}
    collection-id: ${AFFINDA_COLLECTION_ID:dummy_collection}
  openrouter:
    api-key: ${OPENROUTER_API_KEY:dummy_key}
